GrabMangaBundle\Entity\MangaEbook:
    type: entity
    table: manga_ebook
    indexes:
        fk_manga_ebook_manga_chapter1_idx:
            columns:
                - manga_chapter_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        urlMask:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: url_mask
        listPage:
            type: string
            nullable: false
            length: 4000
            options:
                fixed: false
            column: list_page
        listFormat:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: list_format
    manyToOne:
        mangaChapter:
            targetEntity: MangaChapter
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                manga_chapter_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
