GrabMangaBundle\Entity\MangaChapter:
    type: entity
    table: manga_chapter
    indexes:
        fk_manga_chapter_mangas1_idx:
            columns:
                - manga_id
        fk_manga_chapter_manga_tome1_idx:
            columns:
                - manga_tome_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        url:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        cover:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        mangaTome:
            targetEntity: MangaTome
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                manga_tome_id:
                    referencedColumnName: id
            orphanRemoval: false
        manga:
            targetEntity: Manga
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                manga_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
