GrabMangaBundle\Entity\MangaMaj:
    type: entity
    table: manga_maj
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        timestamp:
            type: integer
            nullable: false
            options:
                unsigned: false
        countTitle:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: count_title
        countTome:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: count_tome
        countChapter:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: count_chapter
        filename:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
