GrabMangaBundle\Entity\MangaTome:
    type: entity
    table: manga_tome
    indexes:
        fk_manga_tome_manga1_idx:
            columns:
                - manga_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        cover:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        manga:
            targetEntity: Manga
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                manga_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
