GrabMangaBundle\Entity\TokenUser:
    type: entity
    table: token_user
    indexes:
        fk_token_user_user_idx:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        value:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        time:
            type: bigint
            nullable: false
            options:
                unsigned: false
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
