-- MySQL Script generated by MySQL Workbench
-- dim. 29 oct. 2017 10:17:46 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema GrabManga
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GrabManga
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GrabManga` DEFAULT CHARACTER SET utf8 ;
USE `GrabManga` ;

-- -----------------------------------------------------
-- Table `GrabManga`.`manga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrabManga`.`manga` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `synopsis` TEXT NULL DEFAULT NULL,
  `cover` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GrabManga`.`manga_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrabManga`.`manga_action` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `save` TINYINT(1) NOT NULL DEFAULT '0',
  `maj` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

LOCK TABLES `GrabManga`.`manga_action` WRITE;
/*!40000 ALTER TABLE `GrabManga`.`manga_action` DISABLE KEYS */;
INSERT INTO `GrabManga`.`manga_action` VALUES (1,0,0);
/*!40000 ALTER TABLE `GrabManga`.`manga_action` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `GrabManga`.`manga_tome`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrabManga`.`manga_tome` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `manga_id` INT(11) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `cover` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_manga_tome_manga1_idx` (`manga_id` ASC),
  CONSTRAINT `fk_manga_tome_manga1`
    FOREIGN KEY (`manga_id`)
    REFERENCES `GrabManga`.`manga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GrabManga`.`manga_chapter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrabManga`.`manga_chapter` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `manga_id` INT(11) NOT NULL,
  `manga_tome_id` INT(11) NULL DEFAULT NULL,
  `title` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `cover` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_manga_chapter_mangas1_idx` (`manga_id` ASC),
  INDEX `fk_manga_chapter_manga_tome1_idx` (`manga_tome_id` ASC),
  CONSTRAINT `fk_manga_chapter_manga_tome1`
    FOREIGN KEY (`manga_tome_id`)
    REFERENCES `GrabManga`.`manga_tome` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manga_chapter_mangas1`
    FOREIGN KEY (`manga_id`)
    REFERENCES `GrabManga`.`manga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GrabManga`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrabManga`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `profil` VARCHAR(50) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

LOCK TABLES `GrabManga`.`user` WRITE;
/*!40000 ALTER TABLE `GrabManga`.`user` DISABLE KEYS */;
INSERT INTO `GrabManga`.`user` VALUES (1,'user','GrabManga','grab-manga@gmail.com','GrabManga','1ef03ed0cd5863c550128836b28ec3e9');
/*!40000 ALTER TABLE `GrabManga`.`user` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `GrabManga`.`manga_download`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrabManga`.`manga_download` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `manga_id` INT(11) NULL DEFAULT NULL,
  `manga_tome_id` INT(11) NULL DEFAULT NULL,
  `manga_chapter_id` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  `current_page_decode` INT(11) NOT NULL DEFAULT 0,
  `current_page_pdf` INT(11) NOT NULL DEFAULT 0,
  `max_page` INT(11) NOT NULL DEFAULT 0,
  `current_file_zip` INT(11) NOT NULL DEFAULT 0,
  `max_file_zip` INT(11) NOT NULL DEFAULT 0,
  `current` TINYINT(1) NOT NULL DEFAULT 0,
  `finished` TINYINT(1) NOT NULL DEFAULT 0,
  `filesize` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_manga_download_user1_idx` (`user_id` ASC),
  INDEX `fk_manga_download_manga_chapter1_idx` (`manga_chapter_id` ASC),
  INDEX `fk_manga_download_manga_tome1_idx` (`manga_tome_id` ASC),
  INDEX `fk_manga_download_manga1_idx` (`manga_id` ASC),
  CONSTRAINT `fk_manga_download_manga_chapter1`
    FOREIGN KEY (`manga_chapter_id`)
    REFERENCES `GrabManga`.`manga_chapter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manga_download_manga_tome1`
    FOREIGN KEY (`manga_tome_id`)
    REFERENCES `GrabManga`.`manga_tome` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manga_download_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `GrabManga`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manga_download_manga1`
    FOREIGN KEY (`manga_id`)
    REFERENCES `GrabManga`.`manga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GrabManga`.`manga_ebook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrabManga`.`manga_ebook` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `manga_chapter_id` INT(11) NOT NULL,
  `url_mask` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_manga_ebook_manga_chapter1_idx` (`manga_chapter_id` ASC),
  CONSTRAINT `fk_manga_ebook_manga_chapter1`
    FOREIGN KEY (`manga_chapter_id`)
    REFERENCES `GrabManga`.`manga_chapter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GrabManga`.`manga_maj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrabManga`.`manga_maj` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `timestamp` INT(11) NOT NULL,
  `count_title` INT(11) NOT NULL,
  `count_tome` INT(11) NOT NULL,
  `count_chapter` INT(11) NOT NULL,
  `filename` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `GrabManga`.`token_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrabManga`.`token_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `value` VARCHAR(100) NOT NULL,
  `time` BIGINT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_token_user_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_token_user_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `GrabManga`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GrabManga`.`manga_page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrabManga`.`manga_page` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `manga_ebook_id` INT(11) NOT NULL,
  `page` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_manga_page_manga_ebook1_idx` (`manga_ebook_id` ASC),
  CONSTRAINT `fk_manga_page_manga_ebook1`
    FOREIGN KEY (`manga_ebook_id`)
    REFERENCES `GrabManga`.`manga_ebook` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GrabManga`.`manga_favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrabManga`.`manga_favorite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manga_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_favorite_manga1_idx` (`manga_id` ASC),
  INDEX `fk_favorite_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_favorite_manga1`
    FOREIGN KEY (`manga_id`)
    REFERENCES `GrabManga`.`manga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorite_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `GrabManga`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;