security:
    type:     rest
    resource: GrabMangaBundle\Controller\SecurityController

manga:
    type:     rest
    resource: GrabMangaBundle\Controller\MangaController

generate:
    type:     rest
    resource: GrabMangaBundle\Controller\GenerateController