security:
    type:     rest
    resource: GrabMangaBundle\Controller\SecurityController

manga:
    type:     rest
    resource: GrabMangaBundle\Controller\MangaController

manga.tome:
    type:     rest
    resource: GrabMangaBundle\Controller\MangaTomeController

manga.chapter:
    type:     rest
    resource: GrabMangaBundle\Controller\MangaChapterController

manga.download:
    type:     rest
    resource: GrabMangaBundle\Controller\MangaDownloadController

generate:
    type:     rest
    resource: GrabMangaBundle\Controller\GenerateController

download:
    path:     /archive/download/{token}/{id}
    defaults: { _controller: GrabMangaBundle:Archive:download }