services:
    message.service:
            class: GrabMangaBundle\Services\MessageService
            arguments: [ ]

    bdd.service:
            class: GrabMangaBundle\Services\BddService
            arguments: [ "@doctrine" ]

    manga.service:
        class: GrabMangaBundle\Services\MangaService
        arguments: [ "@doctrine", "@validator", "@message.service" ]