services:
#    grab_manga.example:
#        class: GrabMangaBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    message.service:
            class: GrabMangaBundle\Services\MessageService
            arguments: [ ]

    manga.service:
        class: GrabMangaBundle\Services\MangaService
        arguments: [ "@doctrine", "@validator", "@message.service" ]